version: "3.9"

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pg_data: